$(document).ready(function()
{
    $('.modal-close').click(function()
    {
        $('#mostraPontos').hide()
    })
    $('.modal-overlay').click(function()
    {
        $('#mostraPontos').hide()
    })

    $('#cad').click(function()
    {
        $('#mostraPontos').show()
    })

    $('.modal').modal();
    $('.btn-entrar').click(function()
    {
        $('.in').hide()
        $('.app').show()
    })
    $('.btn-cadEntrar').click(function()
    {
        $('.in').hide()
        $('.app').show()
    })
    $('.tooltipped').tooltip();
    $('.d3').click(function()
    {
        $('.mMetaDia').show()
    })
    $('.meta-modal-footer').click(function()
    {
        $('.mMetaDia').hide()
    })
    $('.cadMetaDia').click(function()
    {
        $('.cadMeta').show()
    })
    $('.fechaCadMeta').click(function()
    {
        $('.cadMeta').hide()
    })
    $('.caminhadaDia').click(function()
    {
        $('#caminhadaDia').toggle(1000)
    })

})